//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recomedia_de.Logic.Generic {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Recomedia_de.Logic.Generic.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Average ähnelt.
        /// </summary>
        internal static string Avg {
            get {
                return ResourceManager.GetString("Avg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Considered timespan ähnelt.
        /// </summary>
        internal static string ConsideredTime {
            get {
                return ResourceManager.GetString("ConsideredTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The considered timespan cannot be less than 5s (or 0 for unlimited). ähnelt.
        /// </summary>
        internal static string ConsideredTimeTooSmall {
            get {
                return ResourceManager.GetString("ConsideredTimeTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Idle value ähnelt.
        /// </summary>
        internal static string IdleValue {
            get {
                return ResourceManager.GetString("IdleValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type of idle value ähnelt.
        /// </summary>
        internal static string IdleValueType {
            get {
                return ResourceManager.GetString("IdleValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number of inputs ähnelt.
        /// </summary>
        internal static string InputCount {
            get {
                return ResourceManager.GetString("InputCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Input resolution ähnelt.
        /// </summary>
        internal static string InputResolution {
            get {
                return ResourceManager.GetString("InputResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selected input ähnelt.
        /// </summary>
        internal static string InputSelectIndex {
            get {
                return ResourceManager.GetString("InputSelectIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximum ähnelt.
        /// </summary>
        internal static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Index of maximum value ähnelt.
        /// </summary>
        internal static string MaxIndex {
            get {
                return ResourceManager.GetString("MaxIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximum number of stored input values ähnelt.
        /// </summary>
        internal static string MaxNumber {
            get {
                return ResourceManager.GetString("MaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minimum ähnelt.
        /// </summary>
        internal static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minimum Difference ähnelt.
        /// </summary>
        internal static string MinimumDifference {
            get {
                return ResourceManager.GetString("MinimumDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minimum Difference for rising values ähnelt.
        /// </summary>
        internal static string MinimumDifferenceUpwards {
            get {
                return ResourceManager.GetString("MinimumDifferenceUpwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Index of minimum value ähnelt.
        /// </summary>
        internal static string MinIndex {
            get {
                return ResourceManager.GetString("MinIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;none&gt; ähnelt.
        /// </summary>
        internal static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number of stored input values ähnelt.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Output 1 ähnelt.
        /// </summary>
        internal static string Output1 {
            get {
                return ResourceManager.GetString("Output1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Output 2 ähnelt.
        /// </summary>
        internal static string Output2 {
            get {
                return ResourceManager.GetString("Output2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number of outputs ähnelt.
        /// </summary>
        internal static string OutputCount {
            get {
                return ResourceManager.GetString("OutputCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Index ähnelt.
        /// </summary>
        internal static string OutputIndex {
            get {
                return ResourceManager.GetString("OutputIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selected output ähnelt.
        /// </summary>
        internal static string OutputSelectIndex {
            get {
                return ResourceManager.GetString("OutputSelectIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current value ähnelt.
        /// </summary>
        internal static string ResendCurrent {
            get {
                return ResourceManager.GetString("ResendCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nothing ähnelt.
        /// </summary>
        internal static string ResendNothing {
            get {
                return ResourceManager.GetString("ResendNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last value ähnelt.
        /// </summary>
        internal static string ResendPrevious {
            get {
                return ResourceManager.GetString("ResendPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restart with last value ähnelt.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The function for output 2 cannot be the same as for output 1. ähnelt.
        /// </summary>
        internal static string SameFunction {
            get {
                return ResourceManager.GetString("SameFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Function for output 2 ähnelt.
        /// </summary>
        internal static string SecondaryFunction {
            get {
                return ResourceManager.GetString("SecondaryFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Send upon select ähnelt.
        /// </summary>
        internal static string SelectAction2 {
            get {
                return ResourceManager.GetString("SelectAction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Send upon select ähnelt.
        /// </summary>
        internal static string SelectAction3 {
            get {
                return ResourceManager.GetString("SelectAction3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Function for output 1 ähnelt.
        /// </summary>
        internal static string SelectedFunction {
            get {
                return ResourceManager.GetString("SelectedFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Standard deviation ähnelt.
        /// </summary>
        internal static string StdDev {
            get {
                return ResourceManager.GetString("StdDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update at least every ähnelt.
        /// </summary>
        internal static string UpdateTime {
            get {
                return ResourceManager.GetString("UpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The update period cannot be more than half of the considered timespan (or 0 for no updates between received telegrams). ähnelt.
        /// </summary>
        internal static string UpdateTimeTooLarge {
            get {
                return ResourceManager.GetString("UpdateTimeTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The update period cannot be less than 0.5s (or 0 for no updates between received telegrams). ähnelt.
        /// </summary>
        internal static string UpdateTimeTooSmall {
            get {
                return ResourceManager.GetString("UpdateTimeTooSmall", resourceCulture);
            }
        }
    }
}
